.github/workflows/npm-publish-github-packages.yml	},
	{
		"key": "ps_n",
		"value": "1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-11-14T09:14:28.017Z",
		"lastAccessed": "2025-11-14T09:14:28.017Z"
	},
	{
		"key": "dpr",
		"value": "2.0271050930023193",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-11-14T09:14:28.017Z",
		"lastAccessed": "2025-11-14T09:14:28.017Z"
	},
	{
		"key": "m_pixel_ratio",
		"value": "2.0271050930023193",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-11-14T09:14:28.017Z",
		"lastAccessed": "2025-11-14T09:14:28.017Z"
	},
	{
		"key": "wd",
		"value": "891x1778",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-11-14T09:14:28.017Z",
		"lastAccessed": "2025-11-14T09:14:28.017Z"
	},
	{
		"key": "c_user",
		"value": "61574553304708",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-11-14T09:14:28.017Z",
		"lastAccessed": "2025-11-14T09:14:28.017Z"
	},
	{
		"key": "presence",
		"value": "C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1763111067993%2C%22v%22%3A1%7D",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-11-14T09:14:28.017Z",
		"lastAccessed": "2025-11-14T09:14:28.017Z"
	},
	{
		"key": "fr",
		"value": "10f8RytWKiG1lLeRv.AWcjS91ZEmrknNhTK10oqUT4r6ZZHFpt0ybcKVXenF93ak8N4F8.BpFvHG..AAA.0.0.BpFvHG.AWd22Zyxb6uPUdQZYFSa9mAZXpk",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-11-14T09:14:28.017Z",
		"lastAccessed": "2025-11-14T09:14:28.017Z"
	},
	{
		"key": "xs",
		"value": "41%3APnTLPwIso2wIcQ%3A2%3A1763111057%3A-1%3A-1%3A%3AAcxPneldGmwHoTfVx1MnBK-xgODR-bUGXbcgbG6fxA",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-11-14T09:14:28.017Z",
		"lastAccessed": "2025-11-14T09:14:28.017Z"
	}
]
